### ISSUE TITLE
carry key or value method

### ISSUE THREAD

**Issue by WilliamRusnackAtFord** [BebeSparkelSparkel/functional_pipes#6]
there should be a decorator that carries the key or value so that functions do not have to deal with passing the stored value.

Pipe(1, 2, 3
  ).str_keyed(
  ).carry_key.map(lambda num_str: num_str + 'seconds'
  ).tuple()
((1, '1seconds'), (2, '2seconds'), (3, '3seconds'))

There could also be a dictionary method that passes and modifies a key.
Pipe(1, 2, 3
  ).set['string'].str_keyed(
  ).use['string'].map(lambda num_str: num_str + 'seconds'
  ).tuple()
((1, '1seconds'), (2, '2seconds'), (3, '3seconds'))

**Comment by BebeSparkelSparkel** [comment]
add_key_map_method should be removed when keyed method is added

**Comment by WilliamRusnackAtFord** [comment]
carry_key and re_key complete but need to be abstracted to allow other similar methods to be added.

@BebeSparkelSparkel keyed method is a different kind of property function and needs to be implemented in a different way because it is more of a function wrapper than a separate pipe that needs to be linked again.

**Comment by BebeSparkelSparkel** [comment]
carry_key and re_key has been abstracted
